name: Terraform CI/CD for Game Day Notification

on:
  push:
    branches:
      - master

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.10.3
      
    - name: Initialise
      run: terraform init

    - name: Destroy
      run: terraform destroy -auto-approve

    # - name: Validate
    #   run: terraform validate

    # - name: Plan
    #   run: terraform plan

    # - name: Apply
    #   run: terraform apply -auto-approve